### ISSUE TITLE
Transitive Provenance

### ISSUE THREAD

**Issue by Brend-Smits** [philips-labs/SLSA-Provenance-Action#1]
Multiple layers with file downloads from previous layers. 
Example:
Job 1 creates two artifacts, 1 jar, and 1 provenance file.
Job 2 is depended on job 1 and downloads the artifacts. We should generate a provenance file based on the existing provenance file from job 1

**Comment by JeroenKnoops** [comment]
Provenance files are created on _Build Script_ level. This means one provenance file is create per workflow.

In our assumption 22 hours ago, we though every job created a separate provenance file, so the question how to deal with transitive provenance was valid. Now we know ( #3 ) that multiple jobs create only one file so this issue is not relevant.
